# Generated by Django 5.1.2 on 2024-11-01 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kbkmarket', '0001_initial'),
        ('uygulama_adi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.IntegerField()),
                ('product_a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygulama_adi.product')),
                ('product_b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbkmarket.product2')),
            ],
            options={
                'db_table': 'match_matchedproduct',
                'unique_together': {('product_a_id', 'product_b_id')},
            },
        ),
    ]
